# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comrade/plugins/dkp/rpc/dkp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comrade/plugins/dkp/rpc/dkp.proto',
  package='dkp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!comrade/plugins/dkp/rpc/dkp.proto\x12\x03\x64kp\"7\n\x14LinkCharacterRequest\x12\x11\n\tcharacter\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"\x17\n\x15LinkCharacterResponse2O\n\x03\x44KP\x12H\n\rLinkCharacter\x12\x19.dkp.LinkCharacterRequest\x1a\x1a.dkp.LinkCharacterResponse\"\x00\x62\x06proto3'
)




_LINKCHARACTERREQUEST = _descriptor.Descriptor(
  name='LinkCharacterRequest',
  full_name='dkp.LinkCharacterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='character', full_name='dkp.LinkCharacterRequest.character', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='dkp.LinkCharacterRequest.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=97,
)


_LINKCHARACTERRESPONSE = _descriptor.Descriptor(
  name='LinkCharacterResponse',
  full_name='dkp.LinkCharacterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['LinkCharacterRequest'] = _LINKCHARACTERREQUEST
DESCRIPTOR.message_types_by_name['LinkCharacterResponse'] = _LINKCHARACTERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LinkCharacterRequest = _reflection.GeneratedProtocolMessageType('LinkCharacterRequest', (_message.Message,), {
  'DESCRIPTOR' : _LINKCHARACTERREQUEST,
  '__module__' : 'comrade.plugins.dkp.rpc.dkp_pb2'
  # @@protoc_insertion_point(class_scope:dkp.LinkCharacterRequest)
  })
_sym_db.RegisterMessage(LinkCharacterRequest)

LinkCharacterResponse = _reflection.GeneratedProtocolMessageType('LinkCharacterResponse', (_message.Message,), {
  'DESCRIPTOR' : _LINKCHARACTERRESPONSE,
  '__module__' : 'comrade.plugins.dkp.rpc.dkp_pb2'
  # @@protoc_insertion_point(class_scope:dkp.LinkCharacterResponse)
  })
_sym_db.RegisterMessage(LinkCharacterResponse)



_DKP = _descriptor.ServiceDescriptor(
  name='DKP',
  full_name='dkp.DKP',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=124,
  serialized_end=203,
  methods=[
  _descriptor.MethodDescriptor(
    name='LinkCharacter',
    full_name='dkp.DKP.LinkCharacter',
    index=0,
    containing_service=None,
    input_type=_LINKCHARACTERREQUEST,
    output_type=_LINKCHARACTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DKP)

DESCRIPTOR.services_by_name['DKP'] = _DKP

# @@protoc_insertion_point(module_scope)
